#ifndef __SERVICE_H__
#define __SERVICE_H__

#define SERVICE_LOGIN 0
#define SERVICE_SEND 1
#define SERVICE_LOGOUT 2
#define SERVICE_FRIENDS_LOGIN 3
#define SERVICE_FRIENDS_LOGOUT 4
#define SERVICE_ERROR 5
#define SERVICE_ACK 6
#define SERVICE_LOGOUT_ACK 7
#define SERVICE_FRIENDS_LIST 8
#define SERVICE_EXIT 9
#define SERVICE_EXIT_ACK 10
#define SERVICE_BROADCAST 11

#endif
